// tailwind.config.js
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant":             "#d3e4fe",
        "outline":                     "#6d797e",
        "primary-container":           "#00a3c4",
        "inverse-surface":             "#213145",
        "primary-fixed":               "#b3ebff",
        "on-primary-fixed-variant":    "#004e5f",
        "on-secondary-fixed-variant":  "#3f465c",
        "inverse-primary":             "#5cd5f8",
        "on-surface-variant":          "#3d494d",
        "background":                  "#f8f9ff",
        "surface-container-lowest":    "#ffffff",
        "on-tertiary":                 "#ffffff",
        "secondary-fixed":             "#dae2fd",
        "outline-variant":             "#bcc8cd",
        "on-secondary-container":      "#5c647a",
        "on-tertiary-fixed-variant":   "#444749",
        "on-surface":                  "#0b1c30",
        "tertiary-fixed":              "#e0e3e5",
        "on-primary":                  "#ffffff",
        "surface-container-highest":   "#d3e4fe",
        "secondary-container":         "#dae2fd",
        "on-error":                    "#ffffff",
        "on-background":               "#0b1c30",
        "on-primary-fixed":            "#001f27",
        "surface-container":           "#e5eeff",
        "secondary-fixed-dim":         "#bec6e0",
        "tertiary":                    "#5c5f61",
        "primary-fixed-dim":           "#5cd5f8",
        "primary":                     "#00677d",
        "surface-bright":              "#f8f9ff",
        "tertiary-container":          "#939698",
        "surface":                     "#f8f9ff",
        "on-tertiary-fixed":           "#191c1e",
        "on-secondary-fixed":          "#131b2e",
        "surface-tint":                "#00677d",
        "on-secondary":                "#ffffff",
        "tertiary-fixed-dim":          "#c4c7c9",
        "surface-dim":                 "#cbdbf5",
        "surface-container-high":      "#dce9ff",
        "on-tertiary-container":       "#2b2f30",
        "inverse-on-surface":          "#eaf1ff",
        "surface-container-low":       "#eff4ff",
        "on-error-container":          "#93000a",
        "secondary":                   "#565e74",
        "on-primary-container":        "#00333f",
        "error":                       "#ba1a1a",
        "error-container":             "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        full:    "9999px",
      },
      spacing: {
        xl:              "2.5rem",
        md:              "1rem",
        "margin-mobile": "16px",
        xs:              "0.25rem",
        unit:            "4px",
        lg:              "1.5rem",
        gutter:          "24px",
        sm:              "0.5rem",
        "container-max": "1440px",
      },
      fontFamily: {
        "code-sm":         ["Geist", "sans-serif"],
        "body-md":         ["Inter", "sans-serif"],
        "headline-lg":     ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "label-md":        ["Geist", "sans-serif"],
        display:           ["Geist", "sans-serif"],
        "body-lg":         ["Inter", "sans-serif"],
        "title-lg":        ["Geist", "sans-serif"],
        "headline-md":     ["Geist", "sans-serif"],
      },
      fontSize: {
        "code-sm":        ["12px", { lineHeight: "16px",  fontWeight: "400" }],
        "body-md":        ["14px", { lineHeight: "22px",  fontWeight: "400" }],
        "headline-lg":    ["32px", { lineHeight: "40px",  letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md":       ["13px", { lineHeight: "18px",  letterSpacing: "0.01em", fontWeight: "500" }],
        display:          ["48px", { lineHeight: "56px",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg":        ["16px", { lineHeight: "26px",  fontWeight: "400" }],
        "title-lg":       ["18px", { lineHeight: "24px",  fontWeight: "600" }],
        "headline-md":    ["24px", { lineHeight: "32px",  fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
